#!/usr/bin/env bash

[ -z "$1" ] && exit 1
mullvad account login "$1" >/dev/null 2>&1  || { echo "mullvad failed."; exit 1; }

clear
while IFS= read -r line; do

mullvad relay set location "$line" >/dev/null 2>&1
mullvad connect & IP=$( curl -4 -s https://api.ipify.org ) && echo "[*] IP changed: $IP $(date)" && sleep 120
done < servers.txt
